const http = require('http');
const fs = require('fs');
const path = require('path');
const { DatabaseSync } = require('node:sqlite');

const root = __dirname;
const dbFile = path.resolve(root, process.env.DB_FILE || 'data/expression.sqlite');
fs.mkdirSync(path.dirname(dbFile), { recursive: true });
const portValue = Number(process.env.PORT || 3000);
const port = Number.isInteger(portValue) && portValue > 0 && portValue < 65536 ? portValue : 3000;
const db = new DatabaseSync(dbFile);
db.exec(`PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS resources (id TEXT PRIMARY KEY, kind TEXT NOT NULL, owner TEXT NOT NULL, data TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, owner TEXT NOT NULL, data TEXT NOT NULL, status TEXT NOT NULL, error TEXT, attempts INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit (id INTEGER PRIMARY KEY AUTOINCREMENT, owner TEXT NOT NULL, action TEXT NOT NULL, resource TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);`);
db.exec(`CREATE TABLE IF NOT EXISTS providers (id TEXT PRIMARY KEY, owner TEXT NOT NULL, name TEXT NOT NULL, base_url TEXT NOT NULL, model TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'disabled', usage_count INTEGER NOT NULL DEFAULT 0, last_used_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);`);
db.exec(`CREATE TABLE IF NOT EXISTS team_members (id TEXT PRIMARY KEY, team_owner TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(team_owner, user_id));`);

const seed = { schemaVersion: 4, theme: 'blue', rewrite: { source: '', candidate: '', final: '', status: 'draft', confirmed: false }, expressionRules: { sampleCount: 0, confirmedCount: 0, pendingCount: 0 }, industries: { activeContext: '地产', entries: [], frameworks: [] }, documents: [], documentProjects: [], documentChapters: [], exportRecords: [], rules: [], comments: [], diagnosis: { factsLocked: false }, releases: [], reviews: [] };
const now = () => new Date().toISOString();
const id = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
function json(res, status, body) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(body)); }
function fail(message, status = 400) { const e = new Error(message); e.status = status; throw e; }
function parseBody(req) { return new Promise((resolve, reject) => { let raw = ''; let rejected = false; req.on('data', c => { raw += c; if (Buffer.byteLength(raw) > 5 * 1024 * 1024 && !rejected) { rejected = true; reject(Object.assign(new Error('payload too large'), { status: 413 })); } }); req.on('end', () => { if (rejected) return; try { resolve(raw ? JSON.parse(raw) : {}); } catch (_) { reject(Object.assign(new Error('invalid JSON'), { status: 400 })); } }); }); }
function owner(req) { return String(req.headers['x-user-id'] || 'local-user').slice(0, 100); }
function role(req) { const value = String(req.headers['x-user-role'] || 'owner').toLowerCase(); return ['owner', 'editor', 'reviewer', 'viewer'].includes(value) ? value : 'viewer'; }
const permissions = { owner: ['read', 'write', 'publish', 'review', 'admin'], editor: ['read', 'write'], reviewer: ['read', 'review'], viewer: ['read'] };
function requirePermission(req, permission) { const current = role(req); if (!permissions[current].includes(permission)) fail(`role ${current} cannot ${permission}`, 403); return current; }
function ensureMember(user) { db.prepare('INSERT OR IGNORE INTO team_members(id,team_owner,user_id,role,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id(), 'local-user', user, user === 'local-user' ? 'owner' : 'viewer', now(), now()); }
function listMembers(teamOwner) { return db.prepare('SELECT id,user_id userId,role,created_at createdAt,updated_at updatedAt FROM team_members WHERE team_owner=? ORDER BY created_at').all(teamOwner); }
function audit(user, action, resource, detail) { db.prepare('INSERT INTO audit(owner,action,resource,detail,created_at) VALUES(?,?,?,?,?)').run(user, action, resource, JSON.stringify(detail), now()); }
function resource(user, kind, data, resourceId = id()) { const stamp = now(); const status = data.status || 'active'; db.prepare('INSERT INTO resources(id,kind,owner,data,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(resourceId, kind, user, JSON.stringify(data), status, stamp, stamp); audit(user, 'create', resourceId, { kind, status }); return { id: resourceId, ...data, version: 1, status, createdAt: stamp, updatedAt: stamp }; }
function listResources(user, kind) { return db.prepare('SELECT id,data,version,status,created_at createdAt,updated_at updatedAt FROM resources WHERE owner=? AND kind=? ORDER BY updated_at DESC').all(user, kind).map(x => ({ id: x.id, ...JSON.parse(x.data), version: x.version, status: x.status, createdAt: x.createdAt, updatedAt: x.updatedAt })); }
function pageResources(user, kind, url) { const page = Math.max(1, Number(url.searchParams.get('page') || 1)); const pageSize = Math.min(100, Math.max(1, Number(url.searchParams.get('pageSize') || 20))); const total = db.prepare('SELECT COUNT(*) count FROM resources WHERE owner=? AND kind=?').get(user, kind).count; const items = listResources(user, kind).slice((page - 1) * pageSize, page * pageSize); return { items, page, pageSize, total, totalPages: Math.ceil(total / pageSize) }; }
function updateResource(user, kind, rid, patch) { const row = db.prepare('SELECT * FROM resources WHERE id=? AND owner=? AND kind=?').get(rid, user, kind); if (!row) fail('resource not found', 404); const data = { ...JSON.parse(row.data), ...patch }; const nextStatus = data.status || row.status; const stamp = now(); db.prepare('UPDATE resources SET data=?,version=version+1,status=?,updated_at=? WHERE id=? AND owner=?').run(JSON.stringify(data), nextStatus, stamp, rid, user); audit(user, 'update', rid, patch); return { id: rid, ...data, version: row.version + 1, status: nextStatus, updatedAt: stamp }; }
function validateText(value, name, max = 200000) { if (typeof value !== 'string' || !value.trim() || value.length > max) fail(`${name} is required and must be <= ${max} characters`); return value.trim(); }
function parseDocument(body) { const format = String(body.format || '').toLowerCase(); if (['pdf', 'docx', 'url'].includes(format)) return { status: 'unsupported', format, message: `${format} 解析器未安装或未配置，请安装对应适配器后重试。` }; if (!['markdown', 'md', 'txt', 'text'].includes(format)) fail('format must be markdown, txt, pdf, docx or url'); const values = Array.isArray(body.texts) ? body.texts : [body.text]; if (!values.length || values.some(value => typeof value !== 'string' || !value.trim())) fail('text or texts is required'); const documents = values.map((text, index) => ({ index, text: text.trim(), characters: text.trim().length, lines: text.trim().split(/\r?\n/).length })); return { status: 'parsed', format: format === 'md' ? 'markdown' : format === 'text' ? 'txt' : format, documents, text: documents.length === 1 ? documents[0].text : undefined }; }
function configuredLLM() { return Boolean(process.env.USER_LLM_API_KEY && process.env.USER_LLM_BASE_URL && process.env.USER_LLM_MODEL); }
function providerView(row) { return { id: row.id, name: row.name, baseUrl: row.base_url, model: row.model, status: row.status, usageCount: row.usage_count, lastUsedAt: row.last_used_at }; }
function listProviders(user) { return db.prepare('SELECT id,name,base_url,model,status,usage_count,last_used_at FROM providers WHERE owner=? ORDER BY created_at').all(user).map(providerView); }
function providerInput(body) { const name = validateText(body.name, 'name', 200); const baseUrl = validateText(body.baseUrl, 'baseUrl', 1000); const model = validateText(body.model, 'model', 200); try { new URL(baseUrl); } catch (_) { fail('baseUrl must be a valid URL'); } return { name, baseUrl, model }; }
function updateProviderUsage(user) { const row = db.prepare("SELECT id FROM providers WHERE owner=? AND status='enabled' ORDER BY updated_at DESC LIMIT 1").get(user); if (!row) return; db.prepare('UPDATE providers SET usage_count=usage_count+1,last_used_at=?,updated_at=? WHERE id=? AND owner=?').run(now(), now(), row.id, user); audit(user, 'use', row.id, { kind: 'provider' }); }
function runTask(taskId, user, input) { setImmediate(async () => { try { db.prepare('UPDATE tasks SET status=?,updated_at=? WHERE id=? AND owner=?').run('running', now(), taskId, user); const candidate = await generate(input, user); const snapshot = { ...references(user, input), semanticLayers: { industry: input.industry || '地产', expression: input.expression || '个人表达规则', scenario: input.scenario || '正式项目汇报' }, contentAnalysis: classify(input.source) }; db.prepare('UPDATE tasks SET status=?,data=?,updated_at=? WHERE id=? AND owner=?').run('completed', JSON.stringify({ input, source: input.source, candidate, status: 'completed', ...snapshot }), now(), taskId, user); } catch (e) { db.prepare('UPDATE tasks SET status=?,error=?,updated_at=? WHERE id=? AND owner=?').run('failed', e.message, now(), taskId, user); } }); }
function integrationTaskView(task) { return { taskId: task.id, status: task.status, attempts: task.attempts, error: task.error || null, createdAt: task.createdAt, updatedAt: task.updatedAt, result: task.data ? JSON.parse(task.data) : null }; }
function createTask(user, input) { const source = validateText(input.source, 'source'); const snapshot = { ...references(user, input), semanticLayers: { industry: input.industry || '地产', expression: input.expression || '个人表达规则', scenario: input.scenario || '正式项目汇报' }, contentAnalysis: classify(source) }; const task = resource(user, 'task', { source, input, ...snapshot, status: 'queued', demoMode: input.demoMode === true }, id()); db.prepare('INSERT INTO tasks(id,owner,data,status,attempts,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(task.id, user, JSON.stringify(task), 'queued', 0, now(), now()); runTask(task.id, user, input); return { ...integrationTaskView({ ...task, attempts: 0, error: null, data: JSON.stringify(task), createdAt: task.createdAt, updatedAt: task.updatedAt }), ruleReferences: snapshot.ruleReferences, sourceReferences: snapshot.sourceReferences, semanticLayers: snapshot.semanticLayers, contentAnalysis: snapshot.contentAnalysis }; }
function references(user, input) { return { ruleReferences: (input.ruleReferences || listResources(user, 'rule').filter(x => x.status === 'confirmed').map(x => x.id)), sourceReferences: (input.sourceReferences || input.sourceIds || []) }; }
function classify(source) { const numbers = source.match(/\d+(?:\.\d+)?%?/g) || []; const sentences = source.split(/[。！？\n]/).map(x => x.trim()).filter(Boolean); return { facts: sentences.filter(x => /\d|事实|数据|来源|显示/.test(x)), numbers, citations: sentences.filter(x => /来源|引用|据|报告|研究/.test(x)), opinions: sentences.filter(x => /认为|需要|应当|建议|判断/.test(x)), hypotheses: sentences.filter(x => /可能|预计|推测|假设|或许/.test(x)) }; }
function termConflicts(body) { const terms = Array.isArray(body.terms) ? body.terms : []; const normalized = terms.map(term => String(term).trim().toLocaleLowerCase().replace(/[\s，。；、,.!?！？:：]/g, '')); const conflicts = []; normalized.forEach((term, index) => { normalized.slice(index + 1).forEach((other, offset) => { if (term && term === other) conflicts.push({ terms: [String(terms[index]), String(terms[index + offset + 1])], reason: 'normalized-term-collision' }); }); }); return { conflicts, checked: normalized.filter(Boolean).length, hasConflict: conflicts.length > 0 }; }
function resolveRules(body) { const groups = new Map(); const decisions = body.decisions && typeof body.decisions === 'object' ? body.decisions : {}; const add = (rule, source) => { if (!rule || typeof rule !== 'object' || !String(rule.name || '').trim()) return; const item = { ...rule, name: String(rule.name).trim(), source, priority: Number.isFinite(Number(rule.priority)) ? Number(rule.priority) : 0 }; if (!groups.has(item.name)) groups.set(item.name, []); groups.get(item.name).push(item); }; (Array.isArray(body.personalRules) ? body.personalRules : []).forEach(rule => add(rule, 'personal')); (Array.isArray(body.teamRules) ? body.teamRules : []).forEach(rule => add(rule, 'team')); const mergedRules = []; const conflicts = []; for (const [name, candidates] of groups) { candidates.sort((a, b) => b.priority - a.priority || (a.source === 'personal' ? -1 : 1)); const selectedSource = decisions[name]; const selected = selectedSource === 'personal' || selectedSource === 'team' ? candidates.find(rule => rule.source === selectedSource) : candidates[0]; if (candidates.length > 1) conflicts.push({ name, candidates, selectedSource: selectedSource || null, reason: 'same-name-rule' }); if (selected) mergedRules.push(selected); } const decisionRequired = conflicts.some(conflict => !conflict.selectedSource); return { mergedRules, conflicts, decisionRequired }; }
async function generate(input, user) { if (!configuredLLM()) { if (input.demoMode !== true) fail('USER_LLM_API_KEY, USER_LLM_BASE_URL and USER_LLM_MODEL are required; set demoMode=true for explicit deterministic demo mode', 503); updateProviderUsage(user); return `${input.source.trim()}\n\n[演示模式：未调用外部模型]`; } const response = await fetch(process.env.USER_LLM_BASE_URL, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.USER_LLM_API_KEY}` }, body: JSON.stringify({ model: process.env.USER_LLM_MODEL, messages: [{ role: 'system', content: input.system || '保留事实、数字和原意，按给定规则改写。' }, { role: 'user', content: input.source }], temperature: 0.2 }) }); if (!response.ok) fail(`LLM request failed: ${response.status}`, 502); const result = await response.json(); const text = result.choices?.[0]?.message?.content; if (!text) fail('LLM returned no content', 502); updateProviderUsage(user); return text; }
function state(user) { const settings = db.prepare('SELECT key,value FROM settings WHERE key=?').get(`state:${user}`); const value = settings ? JSON.parse(settings.value) : structuredClone(seed); value.samples = listResources(user, 'sample'); value.documents = listResources(user, 'document'); value.rules = listResources(user, 'rule'); value.contexts = listResources(user, 'context'); return value; }
function backup(user) { return { schemaVersion: seed.schemaVersion, state: state(user), resources: db.prepare('SELECT id,kind,data,version,status,created_at createdAt,updated_at updatedAt FROM resources WHERE owner=? ORDER BY id').all(user).map(row => ({ id: row.id, kind: row.kind, data: JSON.parse(row.data), version: row.version, status: row.status, createdAt: row.createdAt, updatedAt: row.updatedAt })) }; }
function restore(user, body) { if (body.schemaVersion !== seed.schemaVersion) fail(`unsupported schemaVersion: ${body.schemaVersion}`, 400); if (!body.state || typeof body.state !== 'object' || !Array.isArray(body.resources)) fail('invalid backup format'); db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(`state:${user}`, JSON.stringify(body.state)); const statement = db.prepare('INSERT INTO resources(id,kind,owner,data,version,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,version=excluded.version,status=excluded.status,updated_at=excluded.updated_at WHERE resources.owner=excluded.owner'); for (const item of body.resources) { if (!item.id || !item.kind || !item.data || item.owner) fail('invalid backup resource'); const stamp = now(); statement.run(String(item.id), String(item.kind), user, JSON.stringify(item.data), Number.isInteger(item.version) ? item.version : 1, item.status || 'active', item.createdAt || stamp, item.updatedAt || stamp); } audit(user, 'restore', 'backup', { schemaVersion: body.schemaVersion, resourceCount: body.resources.length }); return backup(user); }
function openapi() { const operation = (summary, requestBody, response = 'object') => ({ summary, ...(requestBody ? { requestBody: { required: true, content: { 'application/json': { schema: { type: 'object' }, example: requestBody } } } } : {}), responses: { '200': { description: 'Success', content: { 'application/json': { schema: { type: response } } } }, '400': { description: 'Invalid request' } } }); return { openapi: '3.0.3', info: { title: 'Personal Expression Workbench API', version: '1.0.0', description: '当前工作台的开发者接口目录。' }, servers: [{ url: '/' }], paths: { '/api/health': { get: operation('检查服务健康状态') }, '/api/state': { get: operation('读取当前用户工作台状态'), put: operation('保存当前用户工作台状态', { theme: 'blue' }) }, '/api/rewrite/analyze': { post: operation('分析原文并锁定事实', { source: '待分析文本' }) }, '/api/rewrite/generate': { post: operation('创建异步改写任务', { source: '待改写文本', demoMode: true }, 'object') }, '/api/integrations/tasks': { post: operation('创建插件改写任务', { source: '待改写文本', demoMode: true }) }, '/api/integrations/tasks/{id}': { get: operation('查询插件任务状态') }, '/api/integrations/tasks/{id}/retry': { post: operation('重试插件任务') }, '/api/samples': { get: operation('读取表达样本'), post: operation('创建表达样本', { title: '样本', body: '正文' }) }, '/api/documents/parse': { post: operation('解析 Markdown 或 TXT 文本', { format: 'markdown', text: '# 标题' }) }, '/api/rules/resolve': { post: operation('合并个人规则与团队规则', { personalRules: [], teamRules: [], decisions: {} }) }, '/api/backup': { get: operation('导出当前用户备份') }, '/api/audit': { get: operation('读取当前用户审计记录') }, '/api/providers': { get: operation('读取模型 Provider'), post: operation('创建模型 Provider', { name: 'Provider', baseUrl: 'https://example.com/v1', model: 'model' }), patch: operation('更新模型 Provider', { id: 'provider-id', status: 'enabled' }) } } }; }
async function api(req, res, url) { if (req.method === 'GET' && url.pathname === '/api/openapi') return json(res, 200, openapi()); if (req.method === "GET" && url.pathname === "/api/backup") return json(res, 200, backup(owner(req))); if (req.method === "POST" && url.pathname === "/api/backup/restore") return json(res, 200, restore(owner(req), await parseBody(req))); const user = owner(req); const parts = url.pathname.split('/').filter(Boolean); if (req.method === 'GET' && url.pathname === '/api/health') return json(res, 200, { ok: true, service: 'personal-expression-preview', persistence: 'sqlite', llmConfigured: configuredLLM() }); if (req.method === 'GET' && url.pathname === '/api/team/me') return json(res, 200, { userId: user, role: role(req), permissions: permissions[role(req)] }); if (req.method === 'GET' && url.pathname === '/api/state') { requirePermission(req, 'read'); return json(res, 200, state(user)); } if (req.method === 'PUT' && url.pathname === '/api/state') { requirePermission(req, 'write'); const body = await parseBody(req); db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(`state:${user}`, JSON.stringify({ ...seed, ...body })); audit(user, 'update', 'state', { keys: Object.keys(body), role: role(req) }); return json(res, 200, state(user)); }
   if (parts[1] === 'providers' && ['GET', 'POST', 'PATCH'].includes(req.method)) {
     requirePermission(req, req.method === 'GET' ? 'read' : 'write');
     if (req.method === 'GET') return json(res, 200, { items: listProviders(user), llmConfigured: configuredLLM(), keyStored: false });
     const body = await parseBody(req);
     if (!body || Array.isArray(body) || typeof body !== 'object') fail('invalid provider payload');
     const allowed = ['name', 'baseUrl', 'model', 'status', ...(req.method === 'PATCH' ? ['id'] : [])];
     if (Object.keys(body).some(key => !allowed.includes(key))) fail('provider accepts only name, baseUrl, model and status; API keys are never stored');
     if (body.status !== undefined) { requirePermission(req, 'admin'); if (!['enabled', 'disabled'].includes(body.status)) fail('invalid provider status'); }
     const rid = parts[2] || body.id;
     const current = req.method === 'PATCH' ? listProviders(user).find(item => item.id === rid) : null;
     if (req.method === 'PATCH' && !current) fail('provider not found', 404);
     const data = providerInput({ ...current, ...body });
     const status = body.status || current?.status || 'disabled';
     const providerId = current?.id || id();
     const stamp = now();
     db.exec('BEGIN');
     try {
       if (status === 'enabled') db.prepare("UPDATE providers SET status='disabled' WHERE owner=? AND id<>?").run(user, providerId);
       if (current) db.prepare('UPDATE providers SET name=?,base_url=?,model=?,status=?,updated_at=? WHERE id=? AND owner=?').run(data.name, data.baseUrl, data.model, status, stamp, providerId, user);
       else db.prepare('INSERT INTO providers(id,owner,name,base_url,model,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(providerId, user, data.name, data.baseUrl, data.model, status, stamp, stamp);
       audit(user, current ? 'update' : 'create', providerId, { kind: 'provider', status });
       db.exec('COMMIT');
     } catch (error) { db.exec('ROLLBACK'); throw error; }
     return json(res, current ? 200 : 201, listProviders(user).find(item => item.id === providerId));
   }
   if (req.method === 'POST' && url.pathname === '/api/documents/parse') return json(res, 200, parseDocument(await parseBody(req)));
  if (parts[1] === 'state' && parts.length === 3 && req.method === 'PUT') { const body = await parseBody(req); const current = state(user); current[parts[2]] = body; db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(`state:${user}`, JSON.stringify(current)); audit(user, 'update', 'state', { section: parts[2] }); return json(res, 200, body); }
    const kindMap = { samples: 'sample', documents: 'document', rules: 'rule', contexts: 'context', industries: 'industry', scenarios: 'scenario' }; if (parts[1] && kindMap[parts[1]] && parts.length === 2) { const kind = kindMap[parts[1]]; if (req.method === 'GET') return json(res, 200, listResources(user, kind)); if (req.method === 'POST') { const body = await parseBody(req); if (kind === 'sample') validateText(body.body, 'body'); if (kind === 'document') validateText(body.content, 'content'); if (kind === 'rule') { validateText(body.statement || body.text, 'statement'); body.priority = Number.isFinite(Number(body.priority)) ? Number(body.priority) : 0; body.status = body.status || 'active'; } if (kind === 'context') { validateText(body.industry, 'industry'); validateText(body.scenario || body.name, 'scenario'); body.status = body.status || 'active'; } if (!body.name && kind !== 'sample') fail('name is required'); return json(res, 201, resource(user, kind, body)); } }
   if (parts[1] && kindMap[parts[1]] && req.method === 'PATCH' && parts[2]) return json(res, 200, updateResource(user, kindMap[parts[1]], parts[2], await parseBody(req)));
  if (req.method === 'POST' && url.pathname === '/api/rewrite/analyze') { const input = await parseBody(req); const source = validateText(input.source, 'source'); const numbers = source.match(/\b\d+(?:\.\d+)?%?\b/g) || []; return json(res, 200, { source, ready: true, lockedContent: { numbers, facts: source.split(/[。！？\n]/).filter(Boolean) }, issues: [], analyzedAt: now() }); }
    if (req.method === 'POST' && url.pathname === '/api/rewrite/generate') { const input = await parseBody(req); const source = validateText(input.source, 'source'); const snapshot = { ...references(user, input), semanticLayers: { industry: input.industry || '地产', expression: input.expression || '个人表达规则', scenario: input.scenario || '正式项目汇报' }, contentAnalysis: classify(source) }; const task = resource(user, 'task', { source, input, ...snapshot, status: 'queued', demoMode: input.demoMode === true }, id()); db.prepare('INSERT INTO tasks(id,owner,data,status,attempts,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(task.id, user, JSON.stringify(task), 'queued', 0, now(), now()); runTask(task.id, user, input); return json(res, 202, { taskId: task.id, status: 'queued', ...snapshot }); }
    if (parts[1] === 'tasks' && parts[2] && req.method === 'GET') { const task = db.prepare('SELECT id,status,error,data,attempts,created_at createdAt,updated_at updatedAt FROM tasks WHERE id=? AND owner=?').get(parts[2], user); if (!task) fail('task not found', 404); return json(res, 200, { ...task, data: JSON.parse(task.data) }); }
    if (parts[1] === 'tasks' && parts[2] && parts[3] === 'resume' && req.method === 'POST') { const task = db.prepare('SELECT * FROM tasks WHERE id=? AND owner=?').get(parts[2], user); if (!task) fail('task not found', 404); const data = JSON.parse(task.data); const resumeId = id(); db.prepare('INSERT INTO tasks(id,owner,data,status,attempts,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(resumeId, user, JSON.stringify({ ...data, id: resumeId, status: 'queued', resumedFrom: parts[2] }), 'queued', task.attempts + 1, now(), now()); runTask(resumeId, user, data.input || { source: data.source, demoMode: data.demoMode }); return json(res, 202, { taskId: resumeId, status: 'queued', resumedFrom: parts[2] }); }
   if (req.method === 'POST' && parts[1] === 'tasks' && parts[2] && parts[3] === 'retry') { const task = db.prepare('SELECT data FROM tasks WHERE id=? AND owner=?').get(parts[2], user); if (!task) fail('task not found', 404); const data = JSON.parse(task.data); const retryId = id(); db.prepare('INSERT INTO tasks(id,owner,data,status,attempts,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(retryId, user, JSON.stringify({ ...data, id: retryId, status: 'queued' }), 'queued', (task.attempts || 0) + 1, now(), now()); runTask(retryId, user, data.input || { source: data.source, demoMode: data.demoMode }); return json(res, 202, { taskId: retryId, status: 'queued', retriedFrom: parts[2] }); }
    if (req.method === 'GET' && parts[1] === 'versions') return json(res, 200, pageResources(user, 'version', url));
   if (req.method === 'POST' && parts[1] === 'versions') { const body = await parseBody(req); validateText(body.content, 'content'); return json(res, 201, resource(user, 'version', { name: body.name || '表达版本', content: body.content, status: 'draft', confirmed: false })); }
   if (req.method === 'PATCH' && parts[1] === 'versions' && parts[2]) { const body = await parseBody(req); const version = listResources(user, 'version').find(x => x.id === parts[2]); if (!version) fail('version not found', 404); if (body.action === 'rollback') { const current = state(user); current.rewrite.final = version.content; current.rewrite.candidate = version.content; current.rewrite.status = 'confirmed'; db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(`state:${user}`, JSON.stringify(current)); audit(user, 'rollback', parts[2], {}); return json(res, 200, state(user)); } return json(res, 200, updateResource(user, 'version', parts[2], body.action === 'confirm' ? { status: 'confirmed', confirmed: true } : body)); }
   if (req.method === 'GET' && parts[1] === 'reviews') return json(res, 200, listResources(user, 'review'));
   if (req.method === 'POST' && parts[1] === 'reviews') { const body = await parseBody(req); return json(res, 201, resource(user, 'review', { name: body.name || '待审批内容', content: body.content || '', status: 'pending', reviewer: body.reviewer || 'team' })); }
    if (req.method === 'PATCH' && parts[1] === 'reviews' && parts[2]) { const body = await parseBody(req); if (!['approved','rejected','pending'].includes(body.status)) fail('invalid review status'); return json(res, 200, updateResource(user, 'review', parts[2], { status: body.status, comment: body.comment || '' })); }
     if (parts[1] === 'comments' && req.method === 'POST') { requirePermission(req, 'review'); const body = await parseBody(req); validateText(body.body || body.comment, 'comment'); return json(res, 201, resource(user, 'comment', { targetId: body.targetId || '', body: body.body || body.comment, status: 'open' })); }
     if (req.method === 'GET' && parts[1] === 'comments') return json(res, 200, pageResources(user, 'comment', url));
     if (req.method === 'PATCH' && parts[1] === 'comments' && parts[2]) { requirePermission(req, 'review'); const body = await parseBody(req); if (!['open', 'approved', 'rejected', 'resolved'].includes(body.status)) fail('invalid comment status'); return json(res, 200, updateResource(user, 'comment', parts[2], { status: body.status })); }
    if (req.method === 'POST' && url.pathname === '/api/terms/conflicts') return json(res, 200, termConflicts(await parseBody(req)));
      if (req.method === 'POST' && url.pathname === '/api/rules/resolve') { const body = await parseBody(req); const result = resolveRules(body); audit(user, 'resolve', 'rules', { conflicts: result.conflicts.map(conflict => ({ name: conflict.name, selectedSource: conflict.selectedSource })), decisionRequired: result.decisionRequired }); return json(res, 200, result); }
     if (req.method === 'GET' && parts[1] === 'releases') return json(res, 200, listResources(user, 'release')); if (req.method === 'POST' && parts[1] === 'releases') { requirePermission(req, 'publish'); const body = await parseBody(req); validateText(body.versionId, 'versionId'); return json(res, 201, resource(user, 'release', { versionId: body.versionId, status: body.status || 'draft', note: body.note || '' })); }
     if (req.method === 'PATCH' && parts[1] === 'releases' && parts[2]) { const body = await parseBody(req); const current = listResources(user, 'release').find(x => x.id === parts[2]); if (!current) fail('release not found', 404); const next = body.status; if (!['draft', 'published', 'archived'].includes(next)) fail('invalid release status'); if (next === 'published') requirePermission(req, 'publish'); else requirePermission(req, 'write'); const allowed = { draft: ['published', 'archived'], published: ['archived'], archived: [] }; if (next !== current.status && !allowed[current.status].includes(next)) fail('invalid release transition', 409); return json(res, 200, updateResource(user, 'release', parts[2], { status: next, publishedAt: next === 'published' ? now() : current.publishedAt })); }
     if (parts[1] === 'publish-api' && ['GET', 'POST', 'PATCH'].includes(req.method)) { if (req.method !== 'GET') requirePermission(req, 'write'); if (req.method === 'GET') return json(res, 200, listResources(user, 'publishApi')); const body = await parseBody(req); if (req.method === 'POST') return json(res, 201, resource(user, 'publishApi', { name: validateText(body.name || 'API', 'name', 200), path: validateText(body.path || body.endpoint, 'path', 500), endpoint: body.endpoint || body.path || '', status: body.status || 'active', response: body.response || null })); return json(res, 200, updateResource(user, 'publishApi', parts[2], body)); }
    if (req.method === 'POST' && parts[1] === 'exports') { const body = await parseBody(req); return json(res, 201, resource(user, 'export', { versionId: body.versionId || '', format: body.format || 'markdown', status: body.status || 'completed', exportedAt: now() })); }
   if (req.method === 'POST' && url.pathname === '/api/samples/clean') { const body = await parseBody(req); const text = validateText(body.body, 'body'); const analysis = classify(text); return json(res, 200, { mode: 'local-demo', source: 'local-rule-demo', confidence: 0.72, reviewStatus: 'pending', labels: body.labels || [], representative: body.representative === true, cleanedText: text.replace(/\s+/g, ' ').trim(), analysis }); }
   if (req.method === 'POST' && url.pathname === '/api/industry/semantic-extract') { const body = await parseBody(req); const source = validateText(body.source, 'source'); const terms = source.split(/[，。；、\s]+/).filter(Boolean).slice(0, 20); return json(res, 200, { mode: 'local-demo', source: 'local-rule-demo', confidence: 0.72, reviewStatus: 'pending', supported: true, structure: { terms, concepts: terms.slice(0, 5), metrics: (source.match(/\d+(?:\.\d+)?%?/g) || []), judgments: classify(source).opinions, analysisStructure: ['背景', '问题', '策略', '结果'] }, entries: terms.map(term => ({ term, meaning: `待确认：${term}`, status: 'pending', source: 'local-rule-demo', confidence: 0.72, reviewStatus: 'pending' })) }); }
   if (req.method === 'POST' && url.pathname === '/api/rules/generate') { const body = await parseBody(req); const source = validateText(body.source, 'source'); const rule = { name: body.name || '候选表达规则', statement: `从内容中提取：${source.slice(0, 80)}`, source: body.sourceId || 'local-rule-demo', confidence: 0.68, reviewStatus: 'pending', status: 'pending', confirmed: false, demoMode: true }; return json(res, 201, resource(user, 'rule', rule)); }
  if (req.method === 'GET' && url.pathname === '/api/exports/skill') { const current = state(user); const confirmed = listResources(user, 'rule').filter(x => x.confirmed === true || x.status === 'confirmed'); const markdown = `# 个人表达规则 Skill\n\n行业语境：${current.industries.activeContext}\n\n${confirmed.map(x => `- ${x.name || x.statement}`).join('\n') || '暂无已确认规则。'}\n`; return json(res, 200, { markdown, prompt: `保留原意与个人语气。已确认规则数：${confirmed.length}。`, status: confirmed.length ? 'ready' : 'incomplete', confirmedRuleCount: confirmed.length }); }
   if (req.method === 'GET' && url.pathname === '/api/audit') return json(res, 200, db.prepare('SELECT action,resource,detail,created_at createdAt FROM audit WHERE owner=? ORDER BY id DESC LIMIT 200').all(user)); fail('API not found', 404); }
const server = http.createServer(async (req, res) => { try { const url = new URL(req.url, 'http://localhost'); if (url.pathname.startsWith('/api/integrations/tasks')) { const user=owner(req), parts=url.pathname.split('/').filter(Boolean); requirePermission(req, req.method==='GET'?'read':'write'); if(req.method==='POST' && parts.length===3) return json(res,202,{ok:true,data:createTask(user,await parseBody(req))}); const task=db.prepare('SELECT id,status,error,data,attempts,created_at createdAt,updated_at updatedAt FROM tasks WHERE id=? AND owner=?').get(parts[3],user); if(!task) fail('task not found',404); if(req.method==='GET') return json(res,200,{ok:true,data:integrationTaskView(task)}); const data=JSON.parse(task.data); return json(res,202,{ok:true,data:{...createTask(user,data.input||{source:data.source,demoMode:data.demoMode}),retriedFrom:task.id}}); } if (url.pathname.startsWith('/api/')) return await api(req, res, url); const requested = decodeURIComponent(url.pathname); const file = requested === '/' ? '/index.html' : requested; const safe = path.normalize(path.join(root, file)); const allowed = new Set(['.html', '.js', '.css']); if (!safe.startsWith(root) || !fs.existsSync(safe) || fs.statSync(safe).isDirectory() || !allowed.has(path.extname(safe))) return json(res, 404, { error: 'Not found' }); res.writeHead(200, { 'Content-Type': { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' }[path.extname(safe)] }); fs.createReadStream(safe).pipe(res); } catch (e) { json(res, e.status || 500, { error: e.message }); } });
 server.listen(port, () => console.log(`Expression workbench listening on http://localhost:${port}`));
