const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawn } = require('child_process');

const port = 3100 + Math.floor(Math.random() * 500);
const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'expression-api-'));
const dbFile = path.join(tempDir, 'state.sqlite');
const server = spawn(process.execPath, ['server.js'], {
  cwd: __dirname,
  env: { ...process.env, PORT: String(port), DB_FILE: dbFile, ALLOW_HEADER_AUTH: '1' },
  stdio: ['ignore', 'pipe', 'pipe']
});

async function request(method, route, payload, user = 'local-user', userRole = 'owner') {
  const response = await fetch(`http://127.0.0.1:${port}${route}`, {
    method,
    headers: { 'x-user-id': user, 'x-user-role': userRole, ...(payload === undefined ? {} : { 'content-type': 'application/json' }) },
    body: payload === undefined ? undefined : JSON.stringify(payload)
  });
  const body = await response.json();
  return { status: response.status, body };
}

async function waitForServer() {
  for (let attempt = 0; attempt < 50; attempt += 1) {
    try { if ((await request('GET', '/api/health')).status === 200) return; } catch (_) {}
    await new Promise(resolve => setTimeout(resolve, 20));
  }
  throw new Error('server did not start');
}

(async () => {
  await waitForServer();
  const health = await request('GET', '/api/health');
  assert.deepStrictEqual(health.body.ok, true);
  assert.strictEqual(typeof health.body.llmConfigured, 'boolean');
  const openapi = await request('GET', '/api/openapi');
  assert.strictEqual(openapi.status, 200);
  assert.strictEqual(openapi.body.openapi, '3.0.3');
  assert.strictEqual(openapi.body.info.title, '商业运营工作台 API');
  for (const route of ['/api/health', '/api/state', '/api/rewrite/analyze', '/api/rewrite/detect', '/api/rewrite/generate', '/api/samples', '/api/documents/parse', '/api/rules/resolve', '/api/backup', '/api/audit', '/api/providers', '/api/team/members']) assert.ok(openapi.body.paths[route]);
  const parsed = await request('POST', '/api/documents/parse', { format: 'markdown', text: '# 标题\n正文' });
  assert.strictEqual(parsed.body.status, 'parsed'); assert.strictEqual(parsed.body.documents[0].lines, 2);
  const batch = await request('POST', '/api/documents/parse', { format: 'txt', texts: ['甲', '乙'] });
  assert.strictEqual(batch.body.documents.length, 2);
  const unsupported = await request('POST', '/api/documents/parse', { format: 'pdf', text: 'x' });
  assert.strictEqual(unsupported.status, 400);
  const initial = await request('GET', '/api/state');
  const exported = await request('GET', '/api/backup'); assert.strictEqual(exported.body.schemaVersion, 8); assert.ok(Array.isArray(exported.body.resources));
  exported.body.state.theme = 'restored'; const restored = await request('POST', '/api/backup/restore', exported.body); assert.strictEqual(restored.body.state.theme, 'restored');
  assert.strictEqual((await request('POST', '/api/backup/restore', exported.body, 'viewer', 'viewer')).status, 403);
  assert.strictEqual((await request('POST', '/api/backup/restore', { ...exported.body, schemaVersion: 999 })).status, 400);
  assert.strictEqual((await request('POST', '/api/backup/restore', { state: {}, resources: [], schemaVersion: 4, filler: 'x'.repeat(5 * 1024 * 1024) })).status, 413);
  assert.strictEqual(initial.status, 200);
  assert.strictEqual((await request('GET', '/api/providers')).body.keyStored, false);
  assert.strictEqual((await request('POST', '/api/providers', { name: '测试', baseUrl: 'https://example.com/v1', model: 'test', apiKey: 'secret' })).status, 400);
  const provider = await request('POST', '/api/providers', { name: '测试', baseUrl: 'https://example.com/v1', model: 'test' });
  assert.strictEqual(provider.status, 201);
  assert.strictEqual((await request('PATCH', '/api/providers', { id: provider.body.id, status: 'enabled' }, 'viewer', 'viewer')).status, 403);
  assert.strictEqual((await request('PATCH', '/api/providers', { id: provider.body.id, status: 'enabled' })).body.status, 'enabled');
  assert.strictEqual((await request('GET', '/api/llm/session')).body.keyStored, false);
  assert.strictEqual((await request('POST', '/api/llm/session', { baseUrl: 'https://example.com/v1', model: 'test-model', apiKey: 'secret-key-xyz' }, 'viewer', 'viewer')).status, 403);
  assert.strictEqual((await request('POST', '/api/llm/session', { baseUrl: 'http://example.com/v1', model: 'x', apiKey: 'k' })).status, 400);
  assert.strictEqual((await request('POST', '/api/llm/session', { baseUrl: 'https://127.0.0.1/v1', model: 'x', apiKey: 'k' })).status, 400);
  assert.strictEqual((await request('POST', '/api/llm/session', { baseUrl: 'https://169.254.169.254/v1', model: 'x', apiKey: 'k' })).status, 400);
  const session = await request('POST', '/api/llm/session', { baseUrl: 'https://example.com/v1', model: 'test-model', apiKey: 'secret-key-xyz' });
  assert.strictEqual(session.status, 200);
  assert.strictEqual(session.body.configured, true);
  assert.strictEqual(session.body.keyStored, false);
  assert.strictEqual(session.body.keyPresent, true);
  assert.strictEqual(session.body.model, 'test-model');
  assert.strictEqual(session.body.source, 'session');
  assert.ok(!JSON.stringify(session.body).includes('secret-key-xyz'));
  assert.strictEqual((await request('GET', '/api/health')).body.llmConfigured, true);
  assert.ok((await request('GET', '/api/llm/session', undefined, 'other-user')).body.source !== 'session');
  const cleared = await request('DELETE', '/api/llm/session');
  assert.strictEqual(cleared.status, 200);
  assert.ok(cleared.body.source !== 'session');
  assert.ok(!JSON.stringify(cleared.body).includes('secret-key-xyz'));
  const saved = { ...initial.body, theme: 'green' };
  assert.strictEqual((await request('PUT', '/api/state', saved)).body.theme, 'green');
  assert.strictEqual((await request('GET', '/api/state')).body.theme, 'green');
  assert.strictEqual((await request('PUT', '/api/state/theme', 'purple')).body, 'purple');
  assert.strictEqual((await request('POST', '/api/rewrite/analyze', { source: '原始内容' })).body.ready, true);
  const fragment = await request('POST', '/api/rewrite/analyze', { fragment: '客流 12%' });
  assert.strictEqual(fragment.status, 200);
  assert.strictEqual(fragment.body.numberCount, 1);
  assert.ok(fragment.body.lockedContent.numbers.includes('12%'));
  const grouped = await request('POST', '/api/rewrite/analyze', { fragment: '年租金 2,000 万元，位于 4.1 号馆' });
  assert.strictEqual(grouped.status, 200);
  assert.ok(grouped.body.lockedContent.numbers.includes('2,000'));
  assert.ok(grouped.body.lockedContent.numbers.includes('4.1'));
  assert.ok(!grouped.body.lockedContent.numbers.includes('000'));
  assert.strictEqual(fragment.body.factsLocked, false);
  const taste = await request('POST', '/api/rewrite/detect', { source: '我们打造完整生态，形成商业矩阵。', intents: ['给内部看'] });
  assert.strictEqual(taste.status, 200);
  assert.ok(taste.body.hits.some(function (hit) { return hit.id === 'buzzwords'; }));
  // 专名里的包装词不算：站名「国际生态会议中心」的「生态」不是作者用词。
  const proper = await request('POST', '/api/rewrite/detect', { source: '从地铁1号线「国际生态会议中心」站步行约10分钟，紧邻贵阳国际生态会议中心。', intents: ['给内部看'] });
  assert.ok(!proper.body.hits.some(function (hit) { return hit.id === 'buzzwords'; }));
  assert.strictEqual((await request('POST', '/api/rewrite/generate', { source: '原始内容', demoMode: true })).status, 400);
  const generated = await request('POST', '/api/rewrite/generate', { source: '原始内容', intent: '给领导的工作汇报', applyStyle: true, demoMode: true });
  assert.strictEqual(generated.status, 202);
  assert.ok(generated.body.taskId);
  let task;
  for (let i = 0; i < 30; i += 1) { task = await request('GET', `/api/tasks/${generated.body.taskId}`); if (task.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.strictEqual(task.body.status, 'completed');
  assert.strictEqual((await request('GET', '/api/providers')).body.items[0].usageCount, 1);
  assert.ok(String(task.body.data.candidate).includes('已加载个人规则：0 条'));
  assert.ok(task.body.data.factDiff);
  assert.strictEqual(task.body.data.factDiff.intact, true);
  assert.strictEqual((await request('POST', '/api/rewrite/generate', { source: '无权限', demoMode: true }, 'viewer', 'viewer')).status, 403);
  const secret = 'secret-key-persist-xyz';
  const leak = await request('POST', '/api/rewrite/generate', { source: '原始内容', intent: '给领导的工作汇报', demoMode: true, llm: { baseUrl: 'https://example.com/v1', model: 'x', apiKey: secret }, apiKey: secret });
  assert.strictEqual(leak.status, 202);
  assert.ok(!JSON.stringify(leak.body).includes(secret));
  let leakTask;
  for (let i = 0; i < 30; i += 1) { leakTask = await request('GET', `/api/tasks/${leak.body.taskId}`); if (leakTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.strictEqual(leakTask.body.status, 'completed');
  assert.ok(!JSON.stringify(leakTask.body).includes(secret));
  assert.deepStrictEqual(task.body.data.ruleReferences, []);
  assert.deepStrictEqual(task.body.data.semanticLayers, { industry: '地产', expression: '个人表达规则', scenario: '给内部看', intent: '给内部看' });
  const audiences = await request('GET', '/api/rewrite/audiences');
  assert.strictEqual(audiences.status, 200);
  assert.deepStrictEqual(audiences.body.map(item => item.id), ['给政府看', '给品牌方看', '给内部看']);
  const exercise = await request('GET', '/api/rewrite/exercise');
  assert.strictEqual(exercise.status, 200);
  assert.ok(String(exercise.body.source).includes('2.1 万'));
  assert.deepStrictEqual(exercise.body.audience, ['给内部看']);
  const multi = await request('POST', '/api/rewrite/generate', { source: '原始内容', intents: ['给政府看', '给内部看'], demoMode: true });
  assert.strictEqual(multi.status, 202);
  let multiTask;
  for (let i = 0; i < 30; i += 1) { multiTask = await request('GET', `/api/tasks/${multi.body.taskId}`); if (multiTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.strictEqual(multiTask.body.status, 'completed');
  assert.strictEqual(multiTask.body.data.semanticLayers.intent, '给政府看、给内部看');
  assert.ok(String(multiTask.body.data.candidate).includes('[这篇写给谁：给政府看、给内部看]'));
  assert.ok(task.body.data.contentAnalysis);
  const sceneTask = await request('POST', '/api/rewrite/generate', { source: '原始内容', scenario: '招商对内汇报', demoMode: true });
  assert.strictEqual(sceneTask.status, 202);
  let sceneResult;
  for (let i = 0; i < 30; i += 1) { sceneResult = await request('GET', `/api/tasks/${sceneTask.body.taskId}`); if (sceneResult.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.strictEqual(sceneResult.body.status, 'completed');
  assert.strictEqual(sceneResult.body.data.semanticLayers.scenario, '招商对内汇报');
  assert.ok(String(sceneResult.body.data.candidate).includes('招商对内汇报'));
  const aliasTask = await request('POST', '/api/rewrite/generate', { source: '原始内容', scene: '运营方案', demoMode: true });
  let aliasResult;
  for (let i = 0; i < 30; i += 1) { aliasResult = await request('GET', `/api/tasks/${aliasTask.body.taskId}`); if (aliasResult.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.strictEqual(aliasResult.body.data.semanticLayers.scenario, '运营方案');
  const integration = await request('POST', '/api/integrations/tasks', { source: '插件改写内容 20%', demoMode: true });
  assert.strictEqual(integration.status, 202); assert.strictEqual(integration.body.ok, true); assert.ok(integration.body.data.taskId);
  const integrationStatus = await request('GET', `/api/integrations/tasks/${integration.body.data.taskId}`);
  assert.strictEqual(integrationStatus.status, 200); assert.ok(['queued', 'running', 'completed'].includes(integrationStatus.body.data.status));
  assert.strictEqual((await request('POST', '/api/integrations/tasks', { source: '无权限', demoMode: true }, 'viewer', 'viewer')).status, 403);
  const integrationRetry = await request('POST', `/api/integrations/tasks/${integration.body.data.taskId}/retry`);
  assert.strictEqual(integrationRetry.status, 202); assert.strictEqual(integrationRetry.body.ok, true);
  const cleaned = await request('POST', '/api/samples/clean', { body: '  客流 12% 可能增长。', labels: ['经营'], representative: true });
  assert.strictEqual(cleaned.body.reviewStatus, 'pending');
  assert.strictEqual(cleaned.body.representative, true);
  assert.ok(cleaned.body.voice && cleaned.body.voice.kind && cleaned.body.voice.style);
  const titled = await request('POST', '/api/samples/clean', { body: '业态组合调整方向' });
  assert.strictEqual(titled.body.voice.kind, '标题写法');
  const judgment = await request('POST', '/api/samples/clean', { body: '本项目需要优化餐饮与零售的组合关系。' });
  assert.strictEqual(judgment.body.voice.kind, '判断句');
  const extracted = await request('POST', '/api/industry/semantic-extract', { source: '客流 12%，需要优化业态组合。' });
  assert.ok(extracted.body.structure.metrics.includes('12%'));
  const extractedMaterial = await request('POST', '/api/industry/semantic-extract', { material: '客流 12%，需要优化业态组合。' });
  assert.ok(extractedMaterial.body.structure.metrics.includes('12%'));
  assert.ok(extractedMaterial.body.terms.length > 0);
  assert.strictEqual(extracted.status, 200);
  assert.strictEqual(extracted.body.mode, 'local-frequency');
  assert.strictEqual(extracted.body.useModel, false);
  assert.ok(Array.isArray(extracted.body.candidates));
  assert.ok(extracted.body.candidates.some(item => item.term.includes('客流') || item.term === '客流'));
  assert.ok(extracted.body.candidates.every(item => item.kind === 'term' || item.kind === 'phrase'));
  const freq = await request('POST', '/api/industry/semantic-extract', { source: '业态组合调整。业态组合决定客流。客流 12%。' });
  assert.strictEqual(freq.body.mode, 'local-frequency');
  const combo = freq.body.candidates.find(item => item.term === '业态组合');
  assert.ok(combo && combo.count >= 2);
  const noisy = await request('POST', '/api/industry/semantic-extract', { source: '这不是空间而是内容。跟贴很多。策展型商业空间里消费者打卡。空间的美学。艺术审美视觉成都。' });
  const noisyTerms = (noisy.body.candidates || []).map(item => item.term);
  ['空间','内容','而是','跟贴','的美学','空间的','艺术','审美','视觉','成都'].forEach(term => {
    assert.ok(!noisyTerms.includes(term), term);
  });
  assert.ok(noisyTerms.some(term => term === '策展型' || term.includes('策展')));
  assert.ok(noisyTerms.some(term => term === '商业空间' || term.includes('商业空间')));
  assert.ok(noisyTerms.some(term => term === '消费者' || term.includes('消费者')));
  const chrome = await request('POST', '/api/industry/semantic-extract', { source: '网易首页 公开课。策展型商业空间里消费者打卡。网易首页 公开课。' });
  const chromeTerms = (chrome.body.candidates || []).map(item => item.term);
  assert.ok(chromeTerms.every(term => !term.includes('网易')));
  assert.ok(!chromeTerms.includes('公开课'));
  assert.ok(chromeTerms.some(term => term.includes('策展')));
  const baiduChrome = await request('POST', '/api/industry/semantic-extract', { source: '百度首页 登录 复制 Baidu copy。策展型商业空间里消费者打卡。百度首页 Baidu copy。' });
  const baiduTerms = (baiduChrome.body.candidates || []).map(item => item.term);
  assert.ok(baiduTerms.every(term => !/百度|baidu|copy|登录|复制/i.test(term)), baiduTerms.join(','));
  assert.ok(baiduTerms.some(term => term.includes('策展')));
  const noAuthorSlice = await request('POST', '/api/industry/semantic-extract', { source: '特色地产诸葛亮写稿。特色地产诸葛亮再写。策展型商业空间里消费者打卡。' });
  const noAuthorTerms = (noAuthorSlice.body.candidates || []).map(item => item.term);
  assert.ok(!noAuthorTerms.includes('产诸葛亮'));
  const planChrome = await request('POST', '/api/industry/semantic-extract', { source: 'Copyright html col 特朗普。商业规划落地。商业规划再写。业态规划落地。业态规划再写。前期策划落地。前期策划再写。' });
  const planTerms = (planChrome.body.candidates || []).map(item => item.term);
  ['Copyright','html','col','特朗普'].forEach(term => assert.ok(!planTerms.includes(term), term));
  assert.ok(planTerms.some(term => term.includes('规划') || term.includes('策划')), planTerms.join(','));
  const forcedModel = await request('POST', '/api/industry/semantic-extract', { source: '客流 12%。', useModel: true });
  if (forcedModel.status === 503) assert.ok(/模型/.test(String(forcedModel.body.error || '')));
  else assert.notStrictEqual(forcedModel.body.mode, 'local-frequency');
  const extractPack = await request('POST', '/api/contexts', { name: '抽词包', terms: ['课时'] });
  assert.strictEqual(extractPack.status, 201);
  const picked = (freq.body.candidates || []).filter(item => item.term === '客流' || item.term === '业态组合').map(item => item.term);
  const mergedTerms = Array.from(new Set(['课时'].concat(picked)));
  const patchedPack = await request('PATCH', `/api/contexts/${extractPack.body.id}`, { terms: mergedTerms });
  assert.strictEqual(patchedPack.status, 200);
  assert.ok(patchedPack.body.terms.includes('课时'));
  assert.ok(patchedPack.body.terms.includes('客流') || patchedPack.body.terms.includes('业态组合'));
  const blockedLocal = await request('POST', '/api/industry/semantic-extract', { url: 'http://127.0.0.1/' });
  assert.strictEqual(blockedLocal.status, 400);
  const blockedHost = await request('POST', '/api/industry/semantic-extract', { source: 'https://localhost/news' });
  assert.strictEqual(blockedHost.status, 400);
  const blockedFile = await request('POST', '/api/industry/semantic-extract', { url: 'file:///etc/passwd' });
  assert.strictEqual(blockedFile.status, 400);
  const blockedLan = await request('POST', '/api/industry/semantic-extract', { url: 'http://192.168.1.8/a' });
  assert.strictEqual(blockedLan.status, 400);
  const blockedMapped = await request('POST', '/api/industry/semantic-extract', { url: 'http://[::ffff:127.0.0.1]/' });
  assert.strictEqual(blockedMapped.status, 400);
  const blockedFetch = await request('POST', '/api/industry/fetch-article', { url: 'http://127.0.0.1/' });
  assert.strictEqual(blockedFetch.status, 400);
  const blockedFetchMapped = await request('POST', '/api/industry/fetch-article', { url: 'http://[::ffff:127.0.0.1]/' });
  assert.strictEqual(blockedFetchMapped.status, 400);
  let manySource = '';
  const manyTerms = [];
  '甲乙丙丁戊己庚辛壬癸'.split('').forEach(a => {
    '子丑寅'.split('').forEach(b => {
      if (manyTerms.length >= 30) return;
      const term = '招商' + a + b;
      manyTerms.push(term);
      manySource += term + '出现。' + term + '再出现。';
    });
  });
  const many = await request('POST', '/api/industry/semantic-extract', { source: manySource });
  assert.ok(many.body.candidates.length > 24);
  const hitPack = await request('POST', '/api/contexts', { name: '重复率包', terms: [] });
  assert.strictEqual(hitPack.status, 201);
  const firstHit = await request('POST', '/api/industry/semantic-extract', { source: '非标能力系统验证。非标能力系统落地。', packId: hitPack.body.id });
  const firstTerm = (firstHit.body.candidates || []).find(item => item.term === '非标能力系统');
  assert.ok(firstTerm && firstTerm.packHits >= 1);
  const secondHit = await request('POST', '/api/industry/semantic-extract', { source: '隐溪川非标能力系统再验证。隐溪川非标能力系统再落地。', packId: hitPack.body.id });
  const secondTerm = (secondHit.body.candidates || []).find(item => item.term === '非标能力系统');
  assert.ok(secondTerm && secondTerm.packHits >= 2);
  const sameArticle = await request('POST', '/api/industry/semantic-extract', { source: '隐溪川非标能力系统再验证。隐溪川非标能力系统再落地。', packId: hitPack.body.id });
  const sameTerm = (sameArticle.body.candidates || []).find(item => item.term === '非标能力系统');
  assert.strictEqual(sameTerm.packHits, secondTerm.packHits);
  const candidate = await request('POST', '/api/rules/generate', { source: '先判断后策略' });
  assert.strictEqual(candidate.body.reviewStatus, 'pending');
  const confirmed = await request('PATCH', `/api/rules/${candidate.body.id}`, { status: 'confirmed', confirmed: true, reviewStatus: 'approved' });
  assert.strictEqual(confirmed.body.confirmed, true);
  const sample = await request('POST', '/api/samples', { title: '样本', body: '真实方案内容', industry: '地产', context: '汇报', representativeness: 'representative', kind: '一段口气', style: '正式汇报', rhythm: '短句落地', logic: '先结论后依据', scene: '招商对内汇报' });
  assert.strictEqual(sample.status, 201);
  assert.strictEqual(sample.body.kind, '一段口气');
  assert.strictEqual(sample.body.rhythm, '短句落地');
  const imported = await request('POST', '/api/samples', { title: '6+7+8号馆业态规划汇报', body: '本项目客流 12%。餐饮与零售需要分开判断。' });
  assert.strictEqual(imported.status, 201);
  assert.ok(imported.body.kind);
  assert.ok(imported.body.body.includes('12%'));
  const rule = await request('POST', '/api/rules', { name: '保留判断', statement: '先判断后策略', confirmed: true, status: 'confirmed' });
  assert.strictEqual(rule.status, 201);
  const calibration = await request('POST', '/api/rules', { name: '场景段展开', statement: '场景段展开到客群一天怎么到店，判断段保持精简', dimension: 'rhythm', scene: '招商对内汇报', sourceRef: '方案二 · 4.1', before: '孟关的客群到店方式多样。', after: '工作日午后，周边亲子客群沿主通道进入，先到儿童业态再到餐饮。', reviewStatus: 'pending' });
  assert.strictEqual(calibration.status, 201);
  assert.ok(calibration.body.id);
  assert.strictEqual(calibration.body.dimension, 'rhythm');
  const fixedCalibration = await request('PATCH', `/api/rules/${calibration.body.id}`, { reviewStatus: 'fixed', confirmed: true, status: 'confirmed' });
  assert.strictEqual(fixedCalibration.status, 200);
  assert.strictEqual(fixedCalibration.body.reviewStatus, 'fixed');
  assert.strictEqual(fixedCalibration.body.confirmed, true);
  const stateWithCalibration = await request('GET', '/api/state');
  const persistedCalibration = (stateWithCalibration.body.rules || []).find(item => item.id === calibration.body.id);
  assert.ok(persistedCalibration);
  assert.strictEqual(persistedCalibration.reviewStatus, 'fixed');
  const ruled = await request('POST', '/api/rewrite/generate', { source: '原始内容', intent: '给领导的工作汇报', applyStyle: true, demoMode: true });
  let ruledTask;
  for (let i = 0; i < 30; i += 1) { ruledTask = await request('GET', `/api/tasks/${ruled.body.taskId}`); if (ruledTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.ok(/已加载个人规则：[1-9]/.test(String(ruledTask.body.data.candidate)));
  assert.ok(/已加载个人语料：[1-9]/.test(String(ruledTask.body.data.candidate)));
  assert.ok(ruledTask.body.data.ruleReferences.length >= 1);
  const skill = await request('GET', '/api/exports/skill');
  assert.strictEqual(skill.status, 200);
  assert.ok(skill.body.markdown && skill.body.prompt && skill.body.confirmedRuleCount >= 1);
  const page = await request('GET', '/api/samples?page=1&pageSize=1');
  assert.ok(Array.isArray(page.body));
  const comment = await request('POST', '/api/comments', { targetId: sample.body.id, body: '请补充来源' });
  assert.strictEqual(comment.status, 201);
  assert.strictEqual((await request('GET', '/api/comments?page=1&pageSize=10')).body.total, 1);
  const release = await request('POST', '/api/releases', { versionId: 'v1' });
  assert.strictEqual(release.body.status, 'draft');
  const published = await request('PATCH', `/api/releases/${release.body.id}`, { status: 'published' });
  assert.strictEqual(published.body.status, 'published');
  assert.strictEqual((await request('PATCH', `/api/releases/${release.body.id}`, { status: 'draft' })).status, 409);
  const apiRecord = await request('POST', '/api/publish-api', { name: '改写 API', path: '/api/rewrite' });
  assert.strictEqual((await request('GET', '/api/publish-api')).body.length, 1);
  assert.strictEqual((await request('PATCH', `/api/publish-api/${apiRecord.body.id}`, { status: 'disabled' })).body.status, 'disabled');
  assert.strictEqual((await request('POST', '/api/releases', { versionId: 'v2' }, 'viewer', 'viewer')).status, 403);
  assert.strictEqual((await request('POST', '/api/comments', { targetId: sample.body.id, body: '无权限' }, 'viewer', 'viewer')).status, 403);
  assert.ok((await request('GET', '/api/audit')).body.length >= 6);
  const conflicts = await request('POST', '/api/terms/conflicts', { terms: ['客流', ' 客流 ', '业态'] });
  assert.strictEqual(conflicts.body.hasConflict, true);
  const resolved = await request('POST', '/api/rules/resolve', { personalRules: [{ name: '语气', statement: '完整', priority: 5 }], teamRules: [{ name: '语气', statement: '统一', priority: 10 }], decisions: {} });
  assert.strictEqual(resolved.body.decisionRequired, true); assert.strictEqual(resolved.body.mergedRules[0].source, 'team');
  const decided = await request('POST', '/api/rules/resolve', { personalRules: [{ name: '语气', statement: '完整', priority: 5 }], teamRules: [{ name: '语气', statement: '统一', priority: 10 }], decisions: { '语气': 'personal' } });
  assert.strictEqual(decided.body.decisionRequired, false); assert.strictEqual(decided.body.mergedRules[0].source, 'personal');
  const resumed = await request('POST', `/api/tasks/${generated.body.taskId}/resume`);
  assert.strictEqual(resumed.status, 202);
  const appJs = await fetch(`http://127.0.0.1:${port}/app.js`);
  assert.strictEqual(appJs.status, 200);
  const blockedServer = await fetch(`http://127.0.0.1:${port}/server.js`);
  assert.strictEqual(blockedServer.status, 404);
  const blockedTest = await fetch(`http://127.0.0.1:${port}/test-api.js`);
  assert.strictEqual(blockedTest.status, 404);
  const locked = await request('POST', '/api/rewrite/analyze', { source: '客流 12%，租金 800 元。', lock: true });
  assert.strictEqual(locked.status, 200);
  assert.strictEqual(locked.body.factsLocked, true);
  assert.ok(locked.body.lockedContent.numbers.includes('12%'));
  assert.ok(locked.body.lockedContent.numbers.includes('800'));
  assert.strictEqual((await request('POST', '/api/rewrite/analyze', { fragment: '客流 12%', lock: true }, 'viewer', 'viewer')).status, 403);
  const drift = await request('POST', '/api/rewrite/generate', { source: '客流 15%。', intent: '给领导的工作汇报', demoMode: true });
  assert.strictEqual(drift.status, 202);
  let driftTask;
  for (let i = 0; i < 30; i += 1) { driftTask = await request('GET', `/api/tasks/${drift.body.taskId}`); if (driftTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.strictEqual(driftTask.body.status, 'completed');
  assert.strictEqual(driftTask.body.data.factDiff.intact, false);
  assert.ok(driftTask.body.data.factDiff.missing.includes('12%'));
  assert.ok(driftTask.body.data.factDiff.missing.includes('800'));
  assert.ok(driftTask.body.data.factDiff.added.includes('15%'));
  const keep = await request('POST', '/api/rewrite/generate', { source: '客流 12%，租金 800 元。', intent: '给领导的工作汇报', demoMode: true });
  let keepTask;
  for (let i = 0; i < 30; i += 1) { keepTask = await request('GET', `/api/tasks/${keep.body.taskId}`); if (keepTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.strictEqual(keepTask.body.data.factDiff.intact, true);
  assert.strictEqual((await request('GET', '/api/team/me')).body.role, 'owner');
  assert.strictEqual((await request('GET', '/api/team/me', undefined, 'spoof-owner', 'owner')).body.role, 'viewer');
  assert.strictEqual((await request('POST', '/api/rewrite/generate', { source: '原始内容', demoMode: true }, 'spoof-owner', 'owner')).status, 403);
  assert.strictEqual((await request('POST', '/api/team/members', { userId: 'x', role: 'editor' }, 'viewer', 'owner')).status, 403);
  assert.strictEqual((await request('POST', '/api/rules/generate', { source: '无权限' }, 'viewer', 'owner')).status, 403);
  const added = await request('POST', '/api/team/members', { userId: 'editor-1', role: 'editor' });
  assert.strictEqual(added.status, 201);
  assert.strictEqual(added.body.role, 'editor');
  assert.strictEqual((await request('GET', '/api/team/me', undefined, 'editor-1', 'viewer')).body.role, 'editor');
  assert.strictEqual((await request('POST', '/api/rewrite/generate', { source: '原始内容', intent: '给领导的工作汇报', demoMode: true }, 'editor-1', 'viewer')).status, 202);
  const patched = await request('PATCH', `/api/team/members/${added.body.id}`, { role: 'reviewer' });
  assert.strictEqual(patched.body.role, 'reviewer');
  assert.strictEqual((await request('POST', '/api/rewrite/generate', { source: '原始内容', demoMode: true }, 'editor-1', 'owner')).status, 403);
  assert.strictEqual((await request('POST', '/api/team/members', { userId: 'local-user', role: 'viewer' })).status, 409);
  const members = await request('GET', '/api/team/members');
  assert.ok(members.body.some(function (row) { return row.userId === 'local-user' && row.role === 'owner'; }));
  // 未登记用户只按访客处理，不落库：否则首屏并发接口会各留一个空账号。
  assert.strictEqual((await request('GET', '/api/team/me', undefined, 'passer-by')).body.role, 'viewer');
  assert.ok(!(await request('GET', '/api/team/members')).body.some(function (row) { return row.userId === 'passer-by'; }));
  const anon = await fetch(`http://127.0.0.1:${port}/api/rewrite/generate`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-user-id': 'local-user', 'x-user-role': 'owner' }, body: JSON.stringify({ source: '原始内容', intent: '给领导的工作汇报', demoMode: true }) });
  assert.strictEqual(anon.status, 202);
  const noHeader = await fetch(`http://127.0.0.1:${port}/api/rewrite/generate`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ source: '原始内容', demoMode: true }) });
  assert.strictEqual(noHeader.status, 403);
  assert.ok(String(noHeader.headers.get('set-cookie') || '').includes('expression-uid='));
  const home = await fetch(`http://127.0.0.1:${port}/`);
  assert.strictEqual(home.status, 200);
  assert.ok(String(home.headers.get('set-cookie') || '').includes('expression-uid='));
  const skillList = await request('GET', '/api/skills');
  assert.strictEqual(skillList.status, 200);
  const skillNames = skillList.body.map(item => item.name);
  ['去 AI 腔', '去空话打分', '先检查再少改', '说人话', '只换说法'].forEach(name => assert.ok(skillNames.includes(name)));
  assert.strictEqual(skillList.body.length, 5);
  assert.ok(!skillNames.includes('清套路'));
  assert.ok(!skillNames.includes('中文去腔'));
  assert.ok(skillList.body.every(item => item.kind === 'generic-deai'));
  const otherSkills = await request('GET', '/api/skills', undefined, 'other-user');
  assert.strictEqual(otherSkills.status, 200);
  assert.strictEqual(otherSkills.body.length, 5);
  const deai = skillList.body.find(item => item.name === '去 AI 腔');
  assert.ok(String(deai.rulesMarkdown).includes('综上所述'));
  assert.ok(String(deai.rulesMarkdown).includes('至关重要'));
  assert.ok(!String(deai.rulesMarkdown).includes('注入灵魂'));
  const keepRules = deai.rulesMarkdown;
  const patchedSkill = await request('PATCH', `/api/skills/${deai.id}`, { enabled: true, rulesMarkdown: 'should-not-overwrite' });
  assert.strictEqual(patchedSkill.status, 200);
  assert.strictEqual(patchedSkill.body.rulesMarkdown, keepRules);
  // 内置写法包是全局一份，归首个创建它的用户。别的用户也要能切换，不能 404。
  await request('POST', '/api/team/members', { userId: 'skill-editor', role: 'editor' });
  const crossPatch = await request('PATCH', `/api/skills/${deai.id}`, { enabled: true }, 'skill-editor');
  assert.strictEqual(crossPatch.status, 200);
  // 按名字提交且命中已有包时应启用它，不新建同名重复项。
  const byName = await request('POST', '/api/skills', { name: '去 AI 腔', enabled: true }, 'skill-editor');
  assert.strictEqual(byName.status, 200);
  const afterNames = await request('GET', '/api/skills', undefined, 'skill-editor');
  assert.strictEqual(afterNames.body.filter(item => item.name === '去 AI 腔').length, 1);
  const missingSkill = await request('POST', '/api/rewrite/generate', { source: '原始内容', intent: '给领导的工作汇报', skillIds: ['skill-not-exist'], demoMode: true });
  assert.strictEqual(missingSkill.status, 400);
  assert.ok(String(missingSkill.body.error).includes('这个改法还不能用'));
  const collapsed = await request('POST', '/api/rewrite/generate', { source: '原始内容', intent: '给领导的工作汇报', skillIds: ['skill-qingtaolu', 'skill-zhongwenquqiang'], demoMode: true });
  assert.strictEqual(collapsed.status, 202);
  assert.ok(collapsed.body.taskId);
  assert.ok(!collapsed.body.taskIds || collapsed.body.taskIds.length === 1);
  let collapsedTask;
  for (let i = 0; i < 30; i += 1) { collapsedTask = await request('GET', `/api/tasks/${collapsed.body.taskId}`); if (collapsedTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.ok(String(collapsedTask.body.data.systemPrompt).includes('去 AI 腔'));
  assert.ok(String(collapsedTask.body.data.systemPrompt).includes('我方'));
  assert.ok(!String(collapsedTask.body.data.systemPrompt).includes('注入灵魂'));
  const pack = await request('POST', '/api/contexts', { name: '教培', terms: ['课时', '续费率'], phrases: ['跟人不跟店'] });
  assert.strictEqual(pack.status, 201);
  assert.strictEqual(pack.body.name, '教培');
  assert.ok(pack.body.terms.includes('课时'));
  assert.strictEqual(pack.body.domain, 'commercial-ops');
  const dual = await request('POST', '/api/rewrite/generate', { source: '原始内容', intent: '给领导的工作汇报', skillIds: ['skill-qingtaolu', 'skill-shuorenhua'], demoMode: true });
  assert.strictEqual(dual.status, 202);
  assert.ok(Array.isArray(dual.body.taskIds));
  assert.strictEqual(dual.body.taskIds.length, 2);
  let dualOne;
  let dualTwo;
  for (let i = 0; i < 30; i += 1) {
    dualOne = await request('GET', `/api/tasks/${dual.body.taskIds[0]}`);
    dualTwo = await request('GET', `/api/tasks/${dual.body.taskIds[1]}`);
    if (dualOne.body.status === 'completed' && dualTwo.body.status === 'completed') break;
    await new Promise(resolve => setTimeout(resolve, 20));
  }
  assert.ok(String(dualOne.body.data.systemPrompt).includes('去 AI 腔'));
  assert.ok(String(dualTwo.body.data.systemPrompt).includes('说人话'));
  assert.ok(String(dualOne.body.data.candidate).includes('[写法包：去 AI 腔]'));
  assert.ok(String(dualTwo.body.data.candidate).includes('[写法包：说人话]'));
  const noStyle = await request('POST', '/api/rewrite/generate', { source: '原始内容', intent: '论文', applyStyle: false, demoMode: true });
  let noStyleTask;
  for (let i = 0; i < 30; i += 1) { noStyleTask = await request('GET', `/api/tasks/${noStyle.body.taskId}`); if (noStyleTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.ok(!String(noStyleTask.body.data.systemPrompt).includes('个人表达（怎么说）'));
  assert.ok(!String(noStyleTask.body.data.candidate).includes('已加载个人规则'));
  const withIndustry = await request('POST', '/api/rewrite/generate', { source: '客流 12%。', intent: '对外沟通', applyIndustry: true, industryPackId: pack.body.id, demoMode: true });
  let industryTask;
  for (let i = 0; i < 30; i += 1) { industryTask = await request('GET', `/api/tasks/${withIndustry.body.taskId}`); if (industryTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.ok(String(industryTask.body.data.systemPrompt).includes('课时'));
  assert.ok(String(industryTask.body.data.systemPrompt).includes('教培'));
  assert.ok(String(industryTask.body.data.candidate).includes('[已换行业用语]'));
  assert.ok(String(industryTask.body.data.candidate).includes('[行业包：教培]'));
  assert.ok(String(industryTask.body.data.candidate).includes('12%'));
  assert.ok(Array.isArray(industryTask.body.data.industryReplacements));
  const mappedPack = await request('POST', '/api/contexts', { name: '映射包', terms: ['客流→课时'] });
  const mapped = await request('POST', '/api/rewrite/generate', { source: '客流 12%。', intent: '对外沟通', applyIndustry: true, industryPackId: mappedPack.body.id, demoMode: true });
  let mappedTask;
  for (let i = 0; i < 30; i += 1) { mappedTask = await request('GET', `/api/tasks/${mapped.body.taskId}`); if (mappedTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.ok(String(mappedTask.body.data.candidate).includes('课时 12%'));
  assert.ok(mappedTask.body.data.industryReplacements.some(item => item.from === '客流' && item.to === '课时'));
  const skillsPage = await fetch(`http://127.0.0.1:${port}/skills.html`);
  assert.strictEqual(skillsPage.status, 200);
  assert.ok((await skillsPage.text()).includes('按去 AI、口气两档看'));
  const rewritePage = await fetch(`http://127.0.0.1:${port}/rewrite.html`);
  assert.strictEqual(rewritePage.status, 200);
  const rewriteHtml = await rewritePage.text();
  assert.ok(rewriteHtml.includes('勾一种改法，出一稿'));
  assert.ok(rewriteHtml.includes('这篇会用到的案例和用词'));
  assert.ok(rewriteHtml.includes('data-related-list'));
  const voicePage = await fetch(`http://127.0.0.1:${port}/voice.html`);
  assert.strictEqual(voicePage.status, 200);
  const voiceHtml = await voicePage.text();
  assert.ok(voiceHtml.includes('data-corpus-filter="scene"'));
  assert.ok(voiceHtml.includes('data-corpus-filter="kind"'));
  const industryPage = await fetch(`http://127.0.0.1:${port}/industry.html`);
  assert.strictEqual(industryPage.status, 200);
  const industryHtml = await industryPage.text();
  assert.ok(industryHtml.includes('从资讯里抽出用词'));
  assert.ok(industryHtml.includes('data-extract-panel'));
  assert.ok(industryHtml.includes('data-extract-run'));
  assert.ok(industryHtml.includes('收下勾上的项目'));
  assert.ok(industryHtml.includes('抽出即进入行业词库'));
  assert.ok(industryHtml.includes('data-extract-url'));
  assert.ok(industryHtml.includes('data-extract-fetch'));
  assert.ok(industryHtml.includes('取这篇'));
  assert.ok(industryHtml.includes('资讯链接'));
  assert.ok(industryHtml.includes('只抽商业运营能用的专名和习惯用语'));
  assert.ok(!industryHtml.includes('建一个行业包'));
  assert.ok(!industryHtml.includes('装进哪个包'));
  assert.ok(industryHtml.includes('这篇属于哪类商业'));
  assert.ok(industryHtml.includes('data-extract-types'));
  const appNav = await (await fetch(`http://127.0.0.1:${port}/app.js`)).text();
  assert.ok(appNav.includes('商业运营工作台'));
  assert.ok(appNav.includes('/api/industry/fetch-article'));
  assert.ok(appNav.includes("name: '资讯'"));
  assert.ok(appNav.includes("name: '术语'"));
  assert.ok(appNav.includes("name: '常用语'"));
  assert.ok(appNav.includes("name: '案例'"));
  const homeHtml = await (await fetch(`http://127.0.0.1:${port}/`)).text();
  assert.ok(homeHtml.includes('商业运营工作台'));
  assert.ok(homeHtml.includes('先养行业资讯，再改一稿'));
  assert.ok(homeHtml.includes('<nav></nav>'));
  const termsPage = await (await fetch(`http://127.0.0.1:${port}/terms.html`)).text();
  assert.ok(termsPage.includes('专名和固定叫法'));
  assert.ok(termsPage.includes('data-term-search'));
  assert.ok(termsPage.includes('data-term-filters'));
  const phrasesPage = await (await fetch(`http://127.0.0.1:${port}/phrases.html`)).text();
  assert.ok(phrasesPage.includes('行业常说的短句'));
  assert.ok(phrasesPage.includes('data-phrase-search'));
  assert.ok(phrasesPage.includes('data-phrase-filters'));
  const casesPage = await (await fetch(`http://127.0.0.1:${port}/cases.html`)).text();
  assert.ok(casesPage.includes('同一项目在两篇'));
  assert.ok(casesPage.includes('data-case-detail'));
  const contexts = await request('GET', '/api/contexts');
  assert.ok(contexts.body.every(item => item.domain === 'commercial-ops'));
  assert.ok(contexts.body.some(item => item.name === '商业运营'));
  const opsPack = contexts.body.find(item => item.name === '商业运营');
  const opsWords = [].concat(opsPack.terms || [], opsPack.phrases || []);
  assert.ok(opsWords.includes('客流') || opsWords.some(term => String(term).includes('客流')));
  assert.strictEqual((await request('POST', '/api/projects', { name: '测试项目', commercialTypes: ['教培'] })).status, 400);
  assert.strictEqual((await request('GET', '/api/projects?type=edu')).status, 400);
  const articleA = await request('POST', '/api/industry/semantic-extract', { source: '成都麓湖是非标商业代表。麓湖主力店稳定。', commercialTypes: ['nonstandard'] });
  assert.strictEqual(articleA.status, 200);
  assert.ok(Array.isArray(articleA.body.projects));
  assert.ok(articleA.body.projects.some(item => item.name.includes('麓湖')));
  assert.ok(!(articleA.body.projects || []).some(item => item.id));
  const articleAAgain = await request('POST', '/api/industry/semantic-extract', { source: '成都麓湖是非标商业代表。麓湖主力店稳定。', commercialTypes: ['nonstandard'] });
  assert.strictEqual(articleAAgain.body.articleId, articleA.body.articleId);
  const luhuOnce = (articleAAgain.body.projects || []).find(item => item.name.includes('麓湖'));
  const luhuFirst = (articleA.body.projects || []).find(item => item.name.includes('麓湖'));
  assert.strictEqual(luhuOnce.articleCount, luhuFirst.articleCount);
  const articleB = await request('POST', '/api/industry/semantic-extract', { source: '隐溪川和麓湖都在做非标。麓湖继续验证主力店。', commercialTypes: ['nonstandard'] });
  const luhu = (articleB.body.projects || []).find(item => item.name.includes('麓湖'));
  assert.ok(luhu && luhu.articleCount >= 2);
  assert.strictEqual(luhu.status, 'candidate');
  assert.ok(!luhu.id);
  const typedBefore = await request('GET', '/api/projects?type=nonstandard');
  assert.ok(!(typedBefore.body || []).some(item => String(item.name || '').includes('麓湖')));
  const accepted = await request('POST', '/api/projects', { name: luhu.name, status: 'accepted', commercialTypes: ['nonstandard'], terms: ['非标商业', '主力店'] });
  assert.ok(accepted.status === 200 || accepted.status === 201);
  assert.strictEqual(accepted.body.status, 'accepted');
  const detail = await request('GET', `/api/projects/${accepted.body.id}`);
  assert.strictEqual(detail.status, 200);
  assert.ok(Array.isArray(detail.body.articles));
  assert.ok(detail.body.articles.length >= 1);
  assert.ok(detail.body.features === undefined || typeof detail.body.features === 'string');
  const typed = await request('GET', '/api/projects?type=nonstandard');
  assert.ok(typed.body.some(item => item.id === accepted.body.id));
  const linked = await request('GET', `/api/industry/links?q=${encodeURIComponent('非标')}`);
  assert.ok(linked.body.projects.some(item => item.name.includes('麓湖')));
  const caseGen = await request('POST', '/api/rewrite/generate', { source: '麓湖非标商业客流 12%。', intent: '给领导的工作汇报', applyIndustry: true, applyStyle: true, demoMode: true });
  let caseTask;
  for (let i = 0; i < 30; i += 1) { caseTask = await request('GET', `/api/tasks/${caseGen.body.taskId}`); if (caseTask.body.status === 'completed') break; await new Promise(resolve => setTimeout(resolve, 20)); }
  assert.ok(Array.isArray(caseTask.body.data.usedCases));
  assert.ok(caseTask.body.data.usedCases.some(name => String(name).includes('麓湖')));
  const prompt = String(caseTask.body.data.systemPrompt);
  assert.ok(prompt.indexOf('行业用语') >= 0);
  assert.ok(prompt.indexOf('相关案例') >= 0);
  assert.ok(prompt.indexOf('个人表达') >= 0);
  assert.ok(prompt.indexOf('行业用语') < prompt.indexOf('个人表达'));
  assert.ok(prompt.includes('12%'));
  assert.ok(String(caseTask.body.data.candidate).includes('12%'));
  assert.ok(String(caseTask.body.data.candidate).includes('相关案例口径'));
  assert.ok(String(caseTask.body.data.candidate).includes('麓湖'));
  const corrected = await request('POST', '/api/rewrite/correct', { generated: '我们需要打造非标商业闭环。', corrected: '我方把非标商业做成可落地的主力店组合。' });
  assert.strictEqual(corrected.status, 200);
  assert.ok(Array.isArray(corrected.body.replacements));
  assert.ok(corrected.body.replacements.some(item => item.from && item.to && item.from !== item.to));
  assert.ok(Array.isArray(corrected.body.habits));
  assert.ok(corrected.body.habits.every(item => typeof item.from === 'string' && typeof item.to === 'string'));
  const acceptedFix = await request('POST', '/api/rewrite/correct/accept', { generated: '我们需要打造非标商业闭环。', corrected: '我方把非标商业做成可落地的主力店组合。', replacements: [{ from: '闭环', to: '主力店组合', kind: 'phrase' }], habits: [{ name: '人工改稿', statement: '「打造闭环」改成「做成主力店组合」', layer: '用词和口径', dimension: 'wording' }], packId: pack.body.id });
  assert.strictEqual(acceptedFix.status, 200);
  assert.strictEqual(acceptedFix.body.habits[0].dimension, 'wording');
  const drill = await request('POST', '/api/industry/drills', { kind: 'wording', packId: pack.body.id });
  assert.strictEqual(drill.status, 200);
  assert.strictEqual(drill.body.kind, 'wording');
  assert.ok(drill.body.prompt);
  const drillBatch = await request('POST', '/api/industry/drills', { kind: 'syntax', count: 12, packId: pack.body.id });
  assert.strictEqual(drillBatch.status, 200);
  assert.strictEqual(drillBatch.body.prompts.length, 12);
  assert.ok(drillBatch.body.prompts.every(item => item.prompt));
  const drillOk = await request('POST', '/api/industry/drills/confirm', { prompt: drill.body.prompt, corrected: '课时按人头算，续费率看跟店还是跟人。', packId: pack.body.id, dimension: 'syntax', scene: '招商方案', habits: [{ name: '人工校对', statement: '不说核心竞争力，改成课时和续费率', layer: '用词和口径' }] });
  assert.strictEqual(drillOk.status, 200);
  assert.ok(drillOk.body.habits.length >= 1);
  assert.strictEqual(drillOk.body.habits[0].dimension, 'syntax');
  const presets = await request('GET', '/api/frameworks/presets');
  assert.strictEqual(presets.status, 200);
  assert.ok(Array.isArray(presets.body) && presets.body.length >= 8);
  assert.ok(presets.body.every(item => item.name && item.priority));
  const consistency = await request('POST', '/api/reports/consistency', { sections: [{ title: '方案二', text: '7.2 预计节约 446 万元，出租率 95%。结论：本次共给出四个方案。' }, { title: '方案三', text: '7.3 预计节约 433 万，出租率 90%。方案一、方案二、方案三如下。' }] });
  assert.strictEqual(consistency.status, 200);
  assert.ok(consistency.body.conflicts.some(item => item.type === 'number'));
  assert.ok(consistency.body.conflicts.some(item => item.type === 'count'));
  const extractTxt = await request('POST', '/api/documents/extract', { filename: '口径.txt', base64: Buffer.from('# 标题\n正文 12%。').toString('base64') });
  assert.strictEqual(extractTxt.status, 200);
  assert.ok(extractTxt.body.text.includes('正文 12%'));
  assert.ok(extractTxt.body.document && extractTxt.body.document.id);
  const parseDocx = await request('POST', '/api/documents/parse', { filename: '口径.txt', base64: Buffer.from('正文 12%').toString('base64') });
  assert.strictEqual(parseDocx.status, 200);
  assert.ok(parseDocx.body.text.includes('12%'));
  for (const format of ['docx', 'pptx']) {
    const exported = await fetch(`http://127.0.0.1:${port}/api/exports/document`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-user-id': 'local-user', 'x-user-role': 'owner' }, body: JSON.stringify({ format: format, title: '测试方案', markdown: '# 方案一\n\n- 要点 A\n- 要点 B\n\n| 指标 | 值 |\n| --- | --- |\n| 租金 | 800 |\n' }) });
    assert.strictEqual(exported.status, 200);
    assert.ok(String(exported.headers.get('content-disposition')).includes('attachment'));
    const buffer = Buffer.from(await exported.arrayBuffer());
    assert.strictEqual(buffer.slice(0, 2).toString('latin1'), 'PK');
  }
  const caseDetailPatch = await request('PATCH', `/api/projects/${accepted.body.id}`, { location: '贵阳', area: '12 万平方米', openedAt: '2024 年 9 月', anchorBrands: ['A', 'B'], highlights: ['首店', '策展'] });
  assert.strictEqual(caseDetailPatch.status, 200);
  assert.strictEqual(caseDetailPatch.body.location, '贵阳');
  assert.deepStrictEqual(caseDetailPatch.body.anchorBrands, ['A', 'B']);
  assert.deepStrictEqual(caseDetailPatch.body.highlights, ['首店', '策展']);
  console.log('API smoke tests passed');
})().catch(error => { console.error(error); process.exitCode = 1; })
  .finally(() => server.kill());
