export const MEMBER_LEVEL_ORDER = { free: 0, trial: 0, starter: 1, pro: 2, annual: 3 }

export const TOOL_REQUIRED_LEVELS = {
  headline: 'free',
  'selling-point': 'free',
  'close-deal': 'free',
  friend: 'free',
  roi: 'free',
  payback: 'free',
  schedule: 'free',
  hook: 'free',
  script: 'free',
  xiaohongshu: 'free',
  'xiaohongshu-education': 'free',
  'douyin-education': 'free',
  'xiaohongshu-beauty': 'free',
  'douyin-beauty': 'free',
  'xiaohongshu-restaurant': 'free',
  'douyin-restaurant': 'free',
  'xiaohongshu-service': 'free',
  'douyin-service': 'free',
  salary: 'starter',
  sop: 'starter',
  'marketing-plan': 'starter',
  'team-training': 'starter',
  fission: 'starter',
  festival: 'starter',
  topic: 'starter',
  'employee-incentive': 'starter',
  'store-opening': 'starter',
  'anniversary-event': 'starter',
  'offseason-traffic': 'starter',
  'experience-service': 'starter',
  'promotion-plan': 'starter',
  'complaint-handling': 'starter',
  'restaurant-health': 'starter',
  'education-health': 'starter',
  'beauty-health': 'starter',
  'xhs-topic': 'starter',
  'xhs-seo': 'starter',
  'xhs-review': 'starter',
  'marketing-calendar': 'pro',
  'price-increase': 'pro',
  'competitor-strategy': 'pro',
  'store-health': 'free',
  meituan: 'pro',
  competitor: 'pro',
  diagnosis: 'pro',
  'business-plan': 'pro',
  'growth-diagnosis': 'pro',
  'xhs-traffic': 'pro',
  'xhs-diagnosis': 'pro',
  'membership-design': 'annual',
  'ip-agent': 'annual',
  'douyin-growth': 'annual',
  'xiaohongshu-growth': 'annual',
  'boss-ip': 'annual',
  'xhs-conversion': 'annual',
  'gross-margin-restaurant': 'free',
  'break-even-restaurant': 'free',
  'turnover-rate-restaurant': 'free',
  'renewal-rate-education': 'free',
  'class-consumption-rate-education': 'free',
  'card-consumption-rate-beauty': 'free',
  'salary-cost-ratio-restaurant': 'free',
  'dish-pricing': 'free',
  'food-waste-rate': 'free',
  'food-yield-rate': 'free',
  'delivery-profit': 'free',
  'delivery-analysis': 'free',
  'inventory-turnover': 'free',
  'dish-contribution': 'free',
  'repurchase-rate': 'free',
  'cup-efficiency': 'free',
  'drink-cost': 'free',
  'payback-restaurant': 'free',
  'cashflow-restaurant': 'free',
  'profit-rate-restaurant': 'free',
  'return-rate-restaurant': 'free',
  'investment-budget': 'free',
  'gross-margin-education': 'free',
  'break-even-education': 'free',
  'salary-cost-ratio-education': 'free',
  'labor-efficiency-education': 'free',
  'venue-utilization-education': 'free',
  'cac-education': 'free',
  'payback-education': 'free',
  'cashflow-education': 'free',
  'profit-rate-education': 'free',
  'return-rate-education': 'free',
  'class-rate-education': 'free',
  'gross-margin-beauty': 'free',
  'break-even-beauty': 'free',
  'salary-cost-ratio-beauty': 'free',
  'labor-efficiency-beauty': 'free',
  'conversion-rate-beauty': 'free',
  'project-profit-beauty': 'free',
  'ltv-beauty': 'free',
  'repurchase-rate-beauty': 'free',
  'payback-beauty': 'free',
  'cashflow-beauty': 'free',
  'profit-rate-beauty': 'free',
  'return-rate-beauty': 'free',
  'project-structure-beauty': 'free',
  'labor-structure-beauty': 'free',
  'card-debt-beauty': 'free',
  'funnel-ltv-beauty': 'free',
  'breakeven-profit-beauty': 'free',
  'device-roi-beauty': 'free',
  'member-card-design-beauty': 'free',
  'channel-cac': 'free',
  'campaign-roi': 'free',
  'referral-roi': 'free',
  'conversion-funnel': 'free',
  'retention-rate': 'free',
  'marketing-budget': 'free',
  'churn-rate': 'free',
  'ltv-restaurant': 'free',
  'ltv-education': 'free',
  'promotion-profit': 'free'
}

const LEVEL_META = {
  free: { badge: '免费', badgeClass: 'badge-free' },
  starter: { badge: '初阶', badgeClass: 'badge-starter' },
  pro: { badge: '进阶', badgeClass: 'badge-pro' },
  annual: { badge: '高阶', badgeClass: 'badge-annual' }
}

export function normalizeMemberLevel(level) {
  return MEMBER_LEVEL_ORDER[level] != null ? level : 'free'
}

export function canAccessLevel(memberLevel, requiredLevel = 'free') {
  return MEMBER_LEVEL_ORDER[normalizeMemberLevel(memberLevel)] >= MEMBER_LEVEL_ORDER[normalizeMemberLevel(requiredLevel)]
}

export function getRequiredMemberLevel(toolCode) {
  return TOOL_REQUIRED_LEVELS[toolCode] || 'free'
}

export function getToolAccessMeta(toolCode) {
  const requiredLevel = getRequiredMemberLevel(toolCode)
  return {
    requiredLevel,
    ...LEVEL_META[normalizeMemberLevel(requiredLevel)]
  }
}
